pipeline {
    agent {
        docker {
            image 'selenium/standalone-chrome'
            args '-v /dev/shm:/dev/shm'
        }
    }
    stages {
        stage('Run Selenium Tests') {
            steps {
                sh 'sleep 10'
                sh 'java -jar /opt/selenium/selenium-server-standalone.jar -port 4444 &'
                sh 'mvn clean test -Dselenium.webdriver.remote.url=http://localhost:4444/wd/hub'
            }
        }
    }
}